<?php

/*
|--------------------------------------------------------------------------
| Data Referensi SIPPM
|--------------------------------------------------------------------------
| Diporting 1:1 dari data JavaScript pada mockup (STATION_MACHINES,
| CONDITION_OPTIONS, ACC_BAGIAN_OPTIONS) supaya daftar Stasiun > Mesin >
| Kategori > Kondisi/Abnormalitas pada Buat Laporan, serta pilihan
| Area/Bagian pada Tambah Akun, identik dengan mockup.
*/

return [

    // Stasiun => daftar Mesin pada stasiun tsb.
    'station_machines' => [
        'gilingan' => [
            'Gilingan 01',
            'Gilingan 02',
            'Gilingan 03',
            'Gilingan 04',
        ],
        'boiler' => [
            'Boiler',
        ],
        'pemurnian' => [
            'Pemanas Nira I / Juice Heater I',
            'Defekator I',
            'Defekator II',
            'Reaction Tank / Sulfitasi',
            'Sulfitasi Tower',
            'Pemanas Nira II / Juice Heater II',
            'Flash Tank',
            'Prefloct Tower',
            'Single Tray Clarifier',
            'Rotary Vacuum Filter (RVF)',
            'Instalasi Pembuatan Gas SO₂ / Sulfur Burner',
            'Instalasi Pembuatan Susu Kapur',
        ],
        'penguapan' => [
            'Evaporator / Badan Penguapan I',
            'Evaporator / Badan Penguapan II',
            'Evaporator / Badan Penguapan III',
            'Evaporator / Badan Penguapan IV',
            'Kondensor',
            'Condensate Pump P801-A',
            'Condensate Pump P801-B',
            'Demin Pump P804-A',
            'Demin Pump P804-B',
        ],
    ],

    // Nama Mesin => [kategori => daftar Kondisi/Abnormalitas]
    'condition_options' => [
        'Gilingan 01' => [
            'mekanik' => [
                'Bearing rusak/aus',
                'Gearbox bermasalah',
                'Gear/pinion aus',
                'Shaft/poros patah atau bengkok',
                'Coupling rusak',
                'Roll gilingan bermasalah',
                'Baut atau sambungan kendor',
                'Getaran mesin berlebihan',
                'Lainnya',
            ],
            'elektrik' => [
                'Motor listrik tidak mau hidup',
                'Motor overheat',
                'Kabel putus',
                'MCB/MCCB trip',
                'Kontaktor rusak',
                'Panel listrik bermasalah',
                'Fuse putus',
                'Gangguan inverter/VFD',
                'Lainnya',
            ],
            'instrumentasi' => [
                'Sensor suhu rusak',
                'Sensor tekanan rusak',
                'Flow meter error',
                'Pressure transmitter bermasalah',
                'Sensor level tidak membaca',
                'Thermocouple rusak',
                'Indikator/gauge tidak akurat',
                'Sistem kontrol otomatis bermasalah',
                'Lainnya',
            ],
            'proses' => [
                'Lainnya',
            ],
        ],
        'Gilingan 02' => [
            'mekanik' => [
                'Bearing rusak/aus',
                'Gearbox bermasalah',
                'Gear/pinion aus',
                'Shaft/poros patah atau bengkok',
                'Coupling rusak',
                'Roll gilingan bermasalah',
                'Baut atau sambungan kendor',
                'Getaran mesin berlebihan',
                'Lainnya',
            ],
            'elektrik' => [
                'Motor listrik tidak mau hidup',
                'Motor overheat',
                'Kabel putus',
                'MCB/MCCB trip',
                'Kontaktor rusak',
                'Panel listrik bermasalah',
                'Fuse putus',
                'Gangguan inverter/VFD',
                'Lainnya',
            ],
            'instrumentasi' => [
                'Sensor suhu rusak',
                'Sensor tekanan rusak',
                'Flow meter error',
                'Pressure transmitter bermasalah',
                'Sensor level tidak membaca',
                'Thermocouple rusak',
                'Indikator/gauge tidak akurat',
                'Sistem kontrol otomatis bermasalah',
                'Lainnya',
            ],
            'proses' => [
                'Lainnya',
            ],
        ],
        'Gilingan 03' => [
            'mekanik' => [
                'Bearing rusak/aus',
                'Gearbox bermasalah',
                'Gear/pinion aus',
                'Shaft/poros patah atau bengkok',
                'Coupling rusak',
                'Roll gilingan bermasalah',
                'Baut atau sambungan kendor',
                'Getaran mesin berlebihan',
                'Lainnya',
            ],
            'elektrik' => [
                'Motor listrik tidak mau hidup',
                'Motor overheat',
                'Kabel putus',
                'MCB/MCCB trip',
                'Kontaktor rusak',
                'Panel listrik bermasalah',
                'Fuse putus',
                'Gangguan inverter/VFD',
                'Lainnya',
            ],
            'instrumentasi' => [
                'Sensor suhu rusak',
                'Sensor tekanan rusak',
                'Flow meter error',
                'Pressure transmitter bermasalah',
                'Sensor level tidak membaca',
                'Thermocouple rusak',
                'Indikator/gauge tidak akurat',
                'Sistem kontrol otomatis bermasalah',
                'Lainnya',
            ],
            'proses' => [
                'Lainnya',
            ],
        ],
        'Gilingan 04' => [
            'mekanik' => [
                'Bearing rusak/aus',
                'Gearbox bermasalah',
                'Gear/pinion aus',
                'Shaft/poros patah atau bengkok',
                'Coupling rusak',
                'Roll gilingan bermasalah',
                'Baut atau sambungan kendor',
                'Getaran mesin berlebihan',
                'Lainnya',
            ],
            'elektrik' => [
                'Motor listrik tidak mau hidup',
                'Motor overheat',
                'Kabel putus',
                'MCB/MCCB trip',
                'Kontaktor rusak',
                'Panel listrik bermasalah',
                'Fuse putus',
                'Gangguan inverter/VFD',
                'Lainnya',
            ],
            'instrumentasi' => [
                'Sensor suhu rusak',
                'Sensor tekanan rusak',
                'Flow meter error',
                'Pressure transmitter bermasalah',
                'Sensor level tidak membaca',
                'Thermocouple rusak',
                'Indikator/gauge tidak akurat',
                'Sistem kontrol otomatis bermasalah',
                'Lainnya',
            ],
            'proses' => [
                'Lainnya',
            ],
        ],
        'Boiler' => [
            'mekanik' => [
                'Boiler Tube bocor',
                'Refractory rusak',
                'Superheater bocor',
                'Economizer bocor',
                'Bearing pompa aus',
                'Mechanical seal bocor',
                'Bearing fan rusak',
                'Impeller fan rusak',
                'Valve macet',
                'Pipa steam bocor',
                'Coupling aus',
                'Lainnya',
            ],
            'elektrik' => [
                'Motor tidak menyala',
                'Motor overheat',
                'Motor trip',
                'MCB/MCCB trip',
                'Kontaktor rusak',
                'Kabel putus',
                'Kabel terbakar',
                'Inverter/VFD error',
                'Relay rusak',
                'Tegangan tidak normal',
                'Grounding bermasalah',
                'Lainnya',
            ],
            'instrumentasi' => [
                'Pressure transmitter error',
                'Temperature sensor rusak',
                'Thermocouple error',
                'Level sensor tidak membaca',
                'Pressure gauge rusak',
                'Temperature gauge error',
                'Flow meter error',
                'Level transmitter error',
                'Pressure switch tidak bekerja',
                'Control valve tidak merespons',
                'PLC/HMI communication error',
                'Lainnya',
            ],
            'proses' => [
                'Lainnya',
            ],
        ],
        'Pemanas Nira I / Juice Heater I' => [
            'mekanik' => [
                'Pipa pemanas bocor',
                'Pipa pemanas tersumbat/berkerak',
                'Kondensat tidak keluar lancar',
                'Valve uap macet',
                'Kebocoran pada sambungan/flange',
                'Lainnya',
            ],
            'elektrik' => [
                'Lainnya',
            ],
            'instrumentasi' => [
                'Suhu nira tidak mencapai ±75°C',
                'Tekanan uap pemanas rendah',
                'Lainnya',
            ],
            'proses' => [
                'Suhu nira tidak mencapai ±75°C',
                'Tekanan uap pemanas rendah',
                'Lainnya',
            ],
        ],
        'Defekator I' => [
            'mekanik' => [
                'Pengaduk tidak berputar',
                'Putaran agitator tidak normal',
                'Aliran susu kapur tidak lancar',
                'Pipa/inlet susu kapur tersumbat',
                'Lainnya',
            ],
            'elektrik' => [
                'Pengaduk tidak berputar',
                'Motor agitator panas',
                'Putaran agitator tidak normal',
                'Lainnya',
            ],
            'instrumentasi' => [
                'pH nira tidak mencapai target ±7,2',
                'Lainnya',
            ],
            'proses' => [
                'pH nira tidak mencapai target ±7,2',
                'Lainnya',
            ],
        ],
        'Defekator II' => [
            'mekanik' => [
                'Agitator berhenti',
                'Endapan/kerak pada bagian dalam',
                'Lainnya',
            ],
            'elektrik' => [
                'Agitator berhenti',
                'Motor overload',
                'Lainnya',
            ],
            'instrumentasi' => [
                'pH tidak mencapai ±9,8',
                'Susu kapur terlalu banyak/kurang',
                'Lainnya',
            ],
            'proses' => [
                'pH tidak mencapai ±9,8',
                'Lainnya',
            ],
        ],
        'Reaction Tank / Sulfitasi' => [
            'mekanik' => [
                'Gas SO₂ tidak masuk',
                'Pipa SO₂ tersumbat',
                'Valve SO₂ macet',
                'Lainnya',
            ],
            'elektrik' => [
                'Lainnya',
            ],
            'instrumentasi' => [
                'pH nira tidak mencapai ±7,2–7,4',
                'Tekanan SO₂ rendah',
                'Lainnya',
            ],
            'proses' => [
                'Gas SO₂ tidak masuk',
                'Reaksi sulfitasi tidak sempurna',
                'Lainnya',
            ],
        ],
        'Sulfitasi Tower' => [
            'mekanik' => [
                'Gas SO₂ tidak terdistribusi merata',
                'Pipa/inlet SO₂ tersumbat',
                'Aliran nira tidak normal',
                'Kebocoran gas SO₂',
                'Lainnya',
            ],
            'elektrik' => [
                'Lainnya',
            ],
            'instrumentasi' => [
                'pH nira tidak sesuai',
                'Lainnya',
            ],
            'proses' => [
                'Gas SO₂ tidak terdistribusi merata',
                'Lainnya',
            ],
        ],
        'Pemanas Nira II / Juice Heater II' => [
            'mekanik' => [
                'Pipa pemanas bocor',
                'Heat transfer menurun karena kerak',
                'Kondensat tidak lancar',
                'Valve uap macet',
                'Lainnya',
            ],
            'elektrik' => [
                'Lainnya',
            ],
            'instrumentasi' => [
                'Suhu nira tidak mencapai ±105°C',
                'Tekanan uap tidak sesuai',
                'Lainnya',
            ],
            'proses' => [
                'Suhu nira tidak mencapai ±105°C',
                'Lainnya',
            ],
        ],
        'Flash Tank' => [
            'mekanik' => [
                'Saluran outlet tersumbat',
                'Kebocoran tangki/pipa',
                'Lainnya',
            ],
            'elektrik' => [
                'Lainnya',
            ],
            'instrumentasi' => [
                'Gas/udara tidak terlepas sempurna',
                'Tekanan tidak stabil',
                'Level nira terlalu tinggi',
                'Lainnya',
            ],
            'proses' => [
                'Lainnya',
            ],
        ],
        'Prefloct Tower' => [
            'mekanik' => [
                'Pompa flokulan tidak bekerja',
                'Pipa flokulan tersumbat',
                'Aliran nira tidak stabil',
                'Lainnya',
            ],
            'elektrik' => [
                'Pompa flokulan tidak bekerja',
                'Lainnya',
            ],
            'instrumentasi' => [
                'Pembentukan flok tidak sempurna',
                'Dosis flokulan terlalu rendah/tinggi',
                'Lainnya',
            ],
            'proses' => [
                'Dosis flokulan terlalu rendah/tinggi',
                'Lainnya',
            ],
        ],
        'Single Tray Clarifier' => [
            'mekanik' => [
                'Saluran nira jernih tersumbat',
                'Scraper/komponen pengumpul lumpur macet (jika terpasang)',
                'Lainnya',
            ],
            'elektrik' => [
                'Lainnya',
            ],
            'instrumentasi' => [
                'Level nira terlalu tinggi/rendah',
                'Lainnya',
            ],
            'proses' => [
                'Pengendapan kotoran terlalu lambat',
                'Nira jernih masih keruh',
                'Flok tidak terbentuk sempurna',
                'Lainnya',
            ],
        ],
        'Rotary Vacuum Filter (RVF)' => [
            'mekanik' => [
                'Vacuum tidak tercapai',
                'Pisau scraper tidak bekerja optimal',
                'Filter cloth tersumbat',
                'Drum tidak berputar',
                'Pompa vacuum bermasalah',
                'Nira tapis tidak mengalir',
                'Lainnya',
            ],
            'elektrik' => [
                'Drum tidak berputar',
                'Motor penggerak overload',
                'Pompa vacuum bermasalah',
                'Lainnya',
            ],
            'instrumentasi' => [
                'Vacuum tidak tercapai',
                'Lainnya',
            ],
            'proses' => [
                'Blotong terlalu tipis/tebal',
                'Lainnya',
            ],
        ],
        'Instalasi Pembuatan Gas SO₂ / Sulfur Burner' => [
            'mekanik' => [
                'Blower tidak bekerja',
                'Pipa gas tersumbat',
                'Kebocoran gas SO₂',
                'Lainnya',
            ],
            'elektrik' => [
                'Blower tidak bekerja',
                'Lainnya',
            ],
            'instrumentasi' => [
                'Suplai udara/O₂ kurang',
                'Lainnya',
            ],
            'proses' => [
                'Belerang tidak terbakar sempurna',
                'Gas SO₂ tidak terbentuk sesuai kebutuhan',
                'Lainnya',
            ],
        ],
        'Instalasi Pembuatan Susu Kapur' => [
            'mekanik' => [
                'Pompa susu kapur tidak bekerja',
                'Mixer tidak berputar',
                'Saluran susu kapur tersumbat',
                'Lainnya',
            ],
            'elektrik' => [
                'Pompa susu kapur tidak bekerja',
                'Mixer tidak berputar',
                'Motor mixer overload',
                'Lainnya',
            ],
            'instrumentasi' => [
                'Konsentrasi/°Be susu kapur tidak sesuai',
                'Lainnya',
            ],
            'proses' => [
                'Konsentrasi/°Be susu kapur tidak sesuai',
                'Lainnya',
            ],
        ],
        'Evaporator / Badan Penguapan I' => [
            'mekanik' => [
                'Tube/calandria bocor',
                'Tube tersumbat kerak',
                'Tube mengalami fouling',
                'Packing manhole bocor',
                'Packing flange rusak',
                'Pipa inlet nira tersumbat',
                'Pipa outlet nira tersumbat',
                'Pipa steam bocor',
                'Valve inlet macet',
                'Valve outlet macet',
                'Valve steam tidak rapat',
                'Korosi shell evaporator',
                'Kebocoran nozzle',
                'Saluran kondensat tersumbat',
                'Lainnya',
            ],
            'elektrik' => [
                'Lainnya',
            ],
            'instrumentasi' => [
                'Temperature sensor error',
                'Temperature transmitter error',
                'Pressure transmitter error',
                'Level transmitter error',
                'Level indicator rusak',
                'Pressure gauge rusak',
                'Alarm high level gagal',
                'Alarm low level gagal',
                'Kabel instrumen putus',
                'Sensor tertutup kerak',
                'Lainnya',
            ],
            'proses' => [
                'Lainnya',
            ],
        ],
        'Evaporator / Badan Penguapan II' => [
            'mekanik' => [
                'Tube calandria bocor',
                'Tube berkerak',
                'Tube fouling',
                'Packing flange bocor',
                'Packing manhole rusak',
                'Pipa steam bocor',
                'Pipa nira tersumbat',
                'Pipa kondensat tersumbat',
                'Valve nira macet',
                'Valve steam rusak',
                'Valve kondensat macet',
                'Nozzle bocor',
                'Korosi shell',
                'Kerusakan support/pengikat',
                'Deposit/endapan berlebih',
                'Lainnya',
            ],
            'elektrik' => [
                'Lainnya',
            ],
            'instrumentasi' => [
                'Temperature transmitter error',
                'Pressure transmitter error',
                'Level transmitter error',
                'Level gauge rusak',
                'Pressure gauge rusak',
                'Sensor temperatur putus',
                'Kabel sensor longgar',
                'Alarm level tidak aktif',
                'Kalibrasi instrumen tidak sesuai',
                'Lainnya',
            ],
            'proses' => [
                'Lainnya',
            ],
        ],
        'Evaporator / Badan Penguapan III' => [
            'mekanik' => [
                'Tube bocor',
                'Tube tersumbat kerak',
                'Fouling tube',
                'Packing flange bocor',
                'Packing manhole rusak',
                'Pipa nira tersumbat',
                'Pipa steam bocor',
                'Pipa kondensat tersumbat',
                'Valve outlet macet',
                'Valve inlet macet',
                'Valve steam bocor',
                'Pipa vakum bocor',
                'Nozzle rusak',
                'Korosi shell',
                'Endapan tebal',
                'Lainnya',
            ],
            'elektrik' => [
                'Lainnya',
            ],
            'instrumentasi' => [
                'Vacuum transmitter error',
                'Pressure transmitter error',
                'Temperature sensor error',
                'Level transmitter error',
                'Vacuum gauge rusak',
                'Pressure gauge rusak',
                'Alarm low vacuum gagal',
                'Kabel sensor putus',
                'Sensor kotor/berkerak',
                'Lainnya',
            ],
            'proses' => [
                'Lainnya',
            ],
        ],
        'Evaporator / Badan Penguapan IV' => [
            'mekanik' => [
                'Tube calandria bocor',
                'Tube berkerak tebal',
                'Fouling berat',
                'Packing flange bocor',
                'Packing manhole rusak',
                'Pipa vakum bocor',
                'Pipa kondensat tersumbat',
                'Pipa nira tersumbat',
                'Valve outlet macet',
                'Valve inlet macet',
                'Valve steam bocor',
                'Nozzle bocor',
                'Korosi shell',
                'Support pipa rusak',
                'Endapan pada permukaan pemanas',
                'Lainnya',
            ],
            'elektrik' => [
                'Lainnya',
            ],
            'instrumentasi' => [
                'Vacuum transmitter error',
                'Temperature sensor error',
                'Pressure transmitter error',
                'Level transmitter error',
                'Vacuum gauge rusak',
                'Temperature transmitter error',
                'Alarm low vacuum gagal',
                'Alarm high level gagal',
                'Kabel transmitter putus',
                'Lainnya',
            ],
            'proses' => [
                'Lainnya',
            ],
        ],
        'Kondensor' => [
            'mekanik' => [
                'Tube kondensor kotor',
                'Tube tersumbat',
                'Tube bocor',
                'Korosi tube',
                'Packing flange bocor',
                'Valve air pendingin macet',
                'Pipa air pendingin bocor',
                'Nozzle rusak',
                'Endapan pada tube',
                'Support kondensor rusak',
                'Lainnya',
            ],
            'elektrik' => [
                'Lainnya',
            ],
            'instrumentasi' => [
                'Temperature sensor error',
                'Vacuum transmitter error',
                'Flow transmitter error',
                'Pressure transmitter error',
                'Vacuum gauge rusak',
                'Temperature transmitter error',
                'Alarm vacuum gagal',
                'Kabel instrumen putus',
                'Lainnya',
            ],
            'proses' => [
                'Lainnya',
            ],
        ],
        'Condensate Pump P801-A' => [
            'mekanik' => [
                'Mechanical seal bocor',
                'Bearing aus',
                'Impeller aus',
                'Impeller tersumbat',
                'Shaft bengkok',
                'Coupling rusak',
                'Casing bocor',
                'Base plate longgar',
                'Pompa kehilangan priming',
                'Alignment motor-pompa tidak tepat',
                'Lainnya',
            ],
            'elektrik' => [
                'Motor overload',
                'Motor overheating',
                'Kabel suplai putus',
                'Kabel terminal longgar',
                'Kontaktor rusak',
                'MCC trip',
                'Bearing motor rusak',
                'Tegangan tidak normal',
                'Lainnya',
            ],
            'instrumentasi' => [
                'Status Run tidak terbaca',
                'Status Fault tidak terbaca',
                'Flow transmitter error',
                'Pressure transmitter error',
                'Alarm pump fault gagal',
                'Lainnya',
            ],
            'proses' => [
                'Lainnya',
            ],
        ],
        'Condensate Pump P801-B' => [
            'mekanik' => [
                'Mechanical seal bocor',
                'Bearing aus',
                'Impeller aus',
                'Impeller tersumbat',
                'Shaft bengkok',
                'Coupling rusak',
                'Casing bocor',
                'Base plate longgar',
                'Pompa kehilangan priming',
                'Alignment pompa tidak tepat',
                'Lainnya',
            ],
            'elektrik' => [
                'Motor overload',
                'Motor overheating',
                'Kabel motor putus',
                'Terminal longgar',
                'Kontaktor rusak',
                'MCC trip',
                'Tegangan suplai rendah/tinggi',
                'Proteksi motor bekerja tanpa kondisi normal',
                'Lainnya',
            ],
            'instrumentasi' => [
                'Status Run tidak terbaca',
                'Status Fault tidak terbaca',
                'Flow transmitter error',
                'Pressure transmitter error',
                'Alarm fault pompa gagal',
                'Lainnya',
            ],
            'proses' => [
                'Lainnya',
            ],
        ],
        'Demin Pump P804-A' => [
            'mekanik' => [
                'Mechanical seal bocor',
                'Bearing aus',
                'Impeller aus',
                'Impeller tersumbat',
                'Shaft bengkok',
                'Coupling rusak',
                'Casing bocor',
                'Base pompa longgar',
                'Pompa kehilangan priming',
                'Alignment motor-pompa tidak tepat',
                'Lainnya',
            ],
            'elektrik' => [
                'Motor overload',
                'Motor overheating',
                'Kabel suplai putus',
                'Terminal kabel longgar',
                'Kontaktor rusak',
                'MCC trip',
                'Tegangan suplai tidak normal',
                'Proteksi motor trip',
                'Lainnya',
            ],
            'instrumentasi' => [
                'Status Run tidak terbaca',
                'Status Fault tidak terbaca',
                'Flow transmitter error',
                'Pressure transmitter error',
                'Alarm pump fault gagal',
                'Lainnya',
            ],
            'proses' => [
                'Lainnya',
            ],
        ],
        'Demin Pump P804-B' => [
            'mekanik' => [
                'Mechanical seal bocor',
                'Bearing aus',
                'Impeller aus',
                'Impeller tersumbat',
                'Shaft bengkok',
                'Coupling rusak',
                'Casing bocor',
                'Base plate longgar',
                'Pompa kehilangan priming',
                'Alignment tidak tepat',
                'Lainnya',
            ],
            'elektrik' => [
                'Motor overload',
                'Motor overheating',
                'Kabel suplai putus',
                'Terminal kabel longgar',
                'Kontaktor rusak',
                'MCC trip',
                'Tegangan tidak normal',
                'Proteksi motor trip',
                'Lainnya',
            ],
            'instrumentasi' => [
                'Status Run tidak terbaca',
                'Status Fault tidak terbaca',
                'Flow transmitter error',
                'Pressure transmitter error',
                'Alarm pump fault gagal',
                'Lainnya',
            ],
            'proses' => [
                'Lainnya',
            ],
        ],
    ],

    // Peran akun => daftar pilihan Area/Stasiun (operator) atau Bagian/Keahlian (teknisi)
    'acc_bagian_options' => [
        'operator' => [
            'Gilingan 01',
            'Gilingan 02',
            'Gilingan 03',
            'Gilingan 04',
        ],
        'teknisi' => [
            'Mekanik',
            'Elektrik',
            'Instrumentasi',
        ],
    ],

    // Label kategori gangguan (dipakai di form & tampilan)
    'category_labels' => [
        'mekanik' => 'Mekanik',
        'elektrik' => 'Elektrik',
        'instrumentasi' => 'Instrumentasi',
        'proses' => 'Proses',
    ],

    // Label stasiun (dipakai di form & tampilan)
    'station_labels' => [
        'gilingan' => 'Gilingan',
        'boiler' => 'Boiler / Ketel',
        'pemurnian' => 'Pemurnian',
        'penguapan' => 'Penguapan (Evaporasi)',
    ],

];
